In [ ]:
import numpy as np

: 

In [81]:
# это просто массив, который может быть N - мерным, и он имеет больше функционала и просто быстрее чем list
data = [0, 9, 4, -1, 20]
arr = np.array(data)
print(arr)



[ 0  9  4 -1 20]


In [8]:

# так можно просто создать мыссив по списку
# так же можно создать просто массив без переменных
# например 
arr = np.array([0, 9, 4, -1, 20])
print(arr)

[ 0  9  4 -1 20]


In [9]:
print(arr)
# выводит массив
print(arr.shape)
# выводит форму массива
print(arr.dtype)
# выводит тип массива
print(arr.ndim)
# выводит сколько мерный этот массив
print(len(arr))
# выводит кол-во элементов в массиве
print(arr.size)
# выводит размер массива

[ 0  9  4 -1 20]
(5,)
int64
1
5
5


In [ ]:
# Типы данных numpy
# int64 - просто числа 64-бита
# float32 - вещественные числа 32 бита
# bool - булевые значения
# complex - комплексные числа
# string - строчные значения
# и тд

In [10]:
# можно указать сразу тип даннах в массиве
arr = np.array([0, 9, 4, -1, 20], dtype = float)
print(arr.dtype)


# еще так можно перевести элементы массива из одного типа данных в другой 
arr = arr.astype(np.int64)
print(arr.dtype)

float64
int64


In [13]:
# по сути так просто array in range(аналог range), можно задавать шаги, а еще есть метод linspace, который выводит конкретное 
# кол-во чисел в промежутке
arr = np.arange(1, 5, 2)
print(arr )

arr = np.linspace(1, 5, 5)
print(arr)

random_arr = np.random.random(5)
print(random_arr)

# как сделать диапазон случайных чисел от A до B
arr = (10 - 5) * np.random.random(5) + 5
print(arr)

[1 3]
[1. 2. 3. 4. 5.]
[0.39527187 0.42120669 0.56498552 0.7466231  0.99507149]
[7.30499545 5.64695487 5.1677099  5.12403825 7.01663924]


In [12]:
# Операции с массивами: sum, sqrt, cos, sin, log exp
arr = np.arange(10)
print(np.sum(arr))

# также можно складывать два массива, умножить, вычитать и делить и  тд
a = np.array([1, 2, 3, 4])
c = np.array([1, 2, 3, 4])
print(a - c)

# еще можно делать все эти операции с одним массивом
arr = np.array([1, 2, 3, 4])
print(arr ** 10)

45
[0 0 0 0]
[      1    1024   59049 1048576]


In [104]:
# Функции агрегаторы
arr = np.random.randint(-5, 10, 10)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())
print(arr.sum())
# и тд
# также можно сравнивать каждый элемент с чем-то
print(arr > 2)

9
-5
1.7
4.838388161361178
17
[ True  True  True False False False False False  True False]


In [108]:
# Манипуляции с массивами
arr2 = np.array([1 ,2 ,36, 6])
arr = np.array([1, 5, 3, 4, 2])
print(np.delete(arr, 2))
print(np.insert(arr, 2, 20))
print(np.sort(arr))
print(np.array_split(arr, 3))

[1 5 4 2]
[ 1  5 20  3  4  2]
[1 2 3 4 5]
[array([1, 5]), array([3, 4]), array([2])]


In [ ]:
# Индексы точно такие-же

In [156]:
# Матрицы и многомерные таблицы
matrix = np.array([(1, 2, 3), (4 ,5, 6), (7, 8, 9)])
print(matrix)
print(matrix.shape)
# показывает количество строк, и столбцов
print(matrix.ndim)
# указывает размерность, так как это матрица он указывает размерность 2
print(matrix.size)
# показывает количество элементов
print(matrix.reshape(1, 9))
# также можно поменять форму матрицы 
matrix2 = np.random.random((3, 3))
print(matrix2)
# можно создать матрицу любого размера с рандомными значениями
np.resize(matrix, (2, 2))
# resize именно вырезает нужную форму из матрицы, а не меняет ее размер


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
[[1 2 3 4 5 6 7 8 9]]
[[0.39742395 0.4397461  0.63146181]
 [0.66478133 0.0743599  0.16130305]
 [0.29325294 0.41065579 0.41848817]]


array([[1, 2],
       [3, 4]])

In [158]:
# Еще можно комбинировать эти функции
matrix = np.arange(16).reshape(4, 4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [195]:
#  Создание специальных матриц
print(np.zeros((4, 4)))
# матрица из нулей
print("===" * 6, end=" \n ")
print(np.ones((4, 4)))
# матрица из единиц
print("===" * 6, end=" \n ")
print(np.full((3, 3), 10))
# матрица из одного значения
print("===" * 6, end=" \n ")
print(np.empty((4, 4)))
# просто пустая матрица

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# В целом операции с матрицами такие же как с массивами

In [212]:
# Axis: 0 - ось строк, 1 - ось столбцов
matrix = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(np.delete(matrix, 1, axis=0))
# удаляет именно строку, тк axis = 0
print("===" * 6, end=" \n ")
print(np.delete(matrix, 1, axis=1))
# удаляет 1 столбец, тк axis = 1
# и так же работают все остальные функции
print(matrix.max())
# максимальный элемент просто в матрице
print(matrix.max(axis=0))
# максимальный элемент именно в строке
matrix

[[1 2 3]
 [7 8 9]]
 [[1 3]
 [4 6]
 [7 9]]
9
[3 6 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [225]:
# Индексация
matrix = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(matrix)
print(matrix[0, 1])
# чтобы найти найти один элемент нужно написать координаты(сначала строка потом столбец)
print(matrix[0])
# чтобы вывести строку нужно просто написать индекс строки  
print(matrix[:,0])
# чтобы вывести столбец нужно написать :, и индекс столбца

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3]
[1 4 7]
