Model without predictors

In [23]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np
import statsmodels.formula.api as smf

In [13]:
df = pd.read_csv("https://stepic.org/media/attachments/course/524/train.csv")
df.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [14]:
df["Sex"] = df["Sex"].map({"male": 1, "female": 0})
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [15]:
df["intercept"] = 1
y = df["Survived"].to_numpy().reshape(-1, 1)

In [16]:
x = df["intercept"].to_numpy().reshape(-1, 1)
df.head(1)

PassengerId  Survived  Pclass                     Name  Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris    1  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  intercept  
0      0  A/5 21171  7.25   NaN        S          1

Model

In [17]:
model = LogisticRegression()

In [18]:
model.fit(x, df['Survived'])

LogisticRegression()

In [25]:
inter = model.intercept_
inter

array([-0.47332458])

In [35]:
np.exp(1.65)

5.206979827179849

In [21]:
model.coef_

array([[3.89506642e-05]])

In [22]:
model.score(x, y)

0.6161616161616161

In [31]:
mode = smf.logit(formula="Survived ~ Sex", data=df).fit()
display(mode.summary())

Optimization terminated successfully.
         Current function value: 0.515041
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Survived   No. Observations:                  891
Model:                          Logit   Df Residuals:                      889
Method:                           MLE   Df Model:                            1
Date:                Wed, 01 Nov 2023   Pseudo R-squ.:                  0.2266
Time:                        01:19:23   Log-Likelihood:                -458.90
converged:                       True   LL-Null:                       -593.33
Covariance Type:            nonrobust   LLR p-value:                 2.020e-60
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.0566      0.129      8.191      0.000       0.804       1.309
Sex           -2.5137      0.167    -15.036      0.000      -2.841      -2.186
==============================================================================
"""

array([1.000000e+00, 3.831008e+22])